// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cache.proto

package com.cache.grpc;

public interface EmptyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Cache.EmptyResponse)
    com.google.protobuf.MessageOrBuilder {
}
