// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cache.proto

package com.cache.grpc;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Cache.NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
