version: '3'
services:
  server1:
    image: cacheserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9527:9527
      - 6749:6749
    environment:
      - SERVER_PORT = 9527
      - RPC_PORT = 6749
    networks:
      - cacheservernet

  server2:
    image: cacheserver
    ports:
      - 9528:9528
      - 6750:6750
    environment:
        - SERVER_PORT = 9528
        - RPC_PORT = 6750
    networks:
      - cacheservernet

  server3:
    image: cacheserver
    ports:
      - 9529:9529
      - 6751:6751
    environment:
      - SERVER_PORT = 9529
      - RPC_PORT = 6751
    networks:
      - cacheservernet

networks:
  cacheservernet:
    driver: bridge